"""Add AI telemetry and granular statuses

Revision ID: 148cd4c6cd4f
Revises: d289e402dc9b
Create Date: 2026-05-08 10:01:47.222994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148cd4c6cd4f'
down_revision: Union[str, Sequence[str], None] = 'd289e402dc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new values to existing Enum type
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'ANALYSIS_PENDING'")
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'ANALYZING'")
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'ANALYSIS_FAILED'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('analysis_attempts', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('analysis_error', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('last_analysis_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_analysis_model')
    op.drop_column('jobs', 'analyzed_at')
    op.drop_column('jobs', 'analysis_error')
    op.drop_column('jobs', 'analysis_attempts')
    # ### end Alembic commands ###
