"""Expand Resume for lineage and optimization

Revision ID: 9802fd3dca44
Revises: a0828d99fedd
Create Date: 2026-05-08 11:01:00.755691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9802fd3dca44'
down_revision: Union[str, Sequence[str], None] = 'a0828d99fedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('optimization_prompt', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('extraction_status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'resumes', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'resumes', 'resumes', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'extraction_status')
    op.drop_column('resumes', 'job_id')
    op.drop_column('resumes', 'optimization_prompt')
    op.drop_column('resumes', 'parent_id')
    # ### end Alembic commands ###
