"""Add safety throttles to User and update schema

Revision ID: bdf567a4d237
Revises: 9802fd3dca44
Create Date: 2026-05-09 22:30:26.883035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf567a4d237'
down_revision: Union[str, Sequence[str], None] = '9802fd3dca44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('applied_resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_applied_resume_id'), 'jobs', ['applied_resume_id'], unique=False)
    op.add_column('resumes', sa.Column('extraction_data', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('confidence_scores', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_currency', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('locked_fields', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('daily_application_limit', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('concurrency_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'concurrency_limit')
    op.drop_column('users', 'daily_application_limit')
    op.drop_column('user_profiles', 'locked_fields')
    op.drop_column('user_profiles', 'preferred_currency')
    op.drop_column('resumes', 'review_status')
    op.drop_column('resumes', 'confidence_scores')
    op.drop_column('resumes', 'extraction_data')
    op.drop_index(op.f('ix_jobs_applied_resume_id'), table_name='jobs')
    op.drop_column('jobs', 'applied_resume_id')
    # ### end Alembic commands ###
