"""Update job model with state management and AI fields

Revision ID: d289e402dc9b
Revises: 4a2bd864cc79
Create Date: 2026-05-08 09:44:52.591774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd289e402dc9b'
down_revision: Union[str, Sequence[str], None] = '4a2bd864cc79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manual creation of the Enum type for Postgres
    job_status = sa.Enum('SCRAPED', 'ANALYZED', 'SHORTLISTED', 'READY_TO_APPLY', 'APPLYING', 'APPLIED', 'FAILED', 'INTERVIEW', 'REJECTED', name='jobstatus')
    job_status.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('status', job_status, nullable=False))
    op.add_column('jobs', sa.Column('ai_score', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('raw_data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_jobs_ai_score'), 'jobs', ['ai_score'], unique=False)
    op.create_index(op.f('ix_jobs_source_id'), 'jobs', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_source_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_ai_score'), table_name='jobs')
    op.drop_column('jobs', 'raw_data')
    op.drop_column('jobs', 'ai_analysis')
    op.drop_column('jobs', 'ai_score')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'source_id')
    # ### end Alembic commands ###
    
    # Manual drop of the Enum type
    sa.Enum(name='jobstatus').drop(op.get_bind(), checkfirst=True)
